### ISSUE TITLE
Triggering a build on new branch/tag added

### ISSUE THREAD

**Issue by LaurentTreguier** [MicrosoftDocs/vsts-docs#2267]
Right now, no build seems to be triggered when a new branch or tag is pushed to a Github repository. #1876 seemed to point towards new tags triggering new builds, but I am getting new builds only when new commits are pushed to already existing branches.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?tabs=yaml&view=vsts#continuous-integration-ci)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vytis** [comment]
I would be interested in this as well - at the moment it just doesn't get triggered when even with `trigger: refs/tags*` added to azure-pipelines.yml

**Comment by lkillgore** [comment]
Hi @vytis, we made a change today, and this should be working now.  Please let me know if it's not.  Thanks!

**Comment by LaurentTreguier** [comment]
Seems to work on my end :+1:

**Comment by DavidStaheli** [comment]
Thanks for your reports and patience on this, @vytis and @LaurentTreguier!  I'm closing this now, but please reopen this issue if we can provide additional help.

**Comment by vytis** [comment]
We are seeing some issues with triggering builds from tags - sometimes nothing happens, sometimes it all works fine. For example we have pushed a commit that triggered [this build](https://dev.azure.com/wireswiss/Wire%20iOS/_build/results?buildId=1190), then pushed a tag immediately afterwards but nothing happened. However when I manually deleted and re-added the same tag all worked fine and [this build](https://dev.azure.com/wireswiss/Wire%20iOS/_build/results?buildId=1194) got triggered

**Comment by gitfool** [comment]
I'd like to trigger a build pipeline when a repo is tagged only; i.e. without requiring new commits (although I'd also like to trigger a build when new commits are pushed).

According to the [sprint 143 release notes](https://docs.microsoft.com/en-us/azure/devops/release-notes/2018/sprint-143-update#azure-pipelines) I should be able to use the following:
```yml
trigger:
  tags:
    include:
    - releases/*
    exclude:
    - releases/old*
```
... but the [yaml schema reference](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md) doesn't mention `tags` and the first entry above uses a branch reference of `refs/tags/*` instead.

So it looks like `tags` aren't supported, as a separate item, and the following shorthand should suffice?
```
trigger:
- master
- refs/tags/*
```

**Comment by solvingj** [comment]
This documentation is still wrong and misleading.  

> YAML builds are configured by default with a CI trigger on all branches and all tags.

In order to build all tags, this must be added to the `azure-pipelines.yml`: 

```
trigger:
  tags:
    include: ['*']
```
However, if you add only this, it makes it so that ONLY tags are built.  So, to get all tags and all branches to build, you need this: 

```
trigger:
  branches:
    include: ['*']
  tags:
    include: ['*']
```

Please update the docs or make it so that new tags are built by default to match the documentation.
