### ISSUE TITLE
How to enable Flaky Test Management

### ISSUE THREAD

**Issue by LyndseyPaxton** [MicrosoftDocs/vsts-docs#5124]
Interesting article and something which I am keen to implement as we currently have several flaky tests. However, in all of my VSTS projects settings, I do not see an option for Project Settings -&gt; Pipelines -&gt; Test Management.

Is this something which needs to be manually enabled?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8dfb3bf-8cce-7ad8-b2c6-40d6c2b9d441
* Version Independent ID: 53e2d39d-6808-70d5-9c26-bc4c5bb109e3
* Content: [Flaky test management - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/flaky-test-management?view=azure-devops#feedback)
* Content Source: [docs/pipelines/test/flaky-test-management.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/test/flaky-test-management.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by ahaleiii** [comment]
This is a new feature so my guess is that they are still rolling it out across organizations.

https://docs.microsoft.com/en-us/azure/devops/release-notes/2019/sprint-155-update#in-product-support-for-flaky-test-management

I'm also excited for this because our team suffers from flaky tests (we've been calling them "non-determinate" tests).

**Comment by gregpakes** [comment]
I am waiting for this too.  However, this update is from July 22.  It is now Aug 6.  Does the roll out take this long?

**Comment by KathrynEE** [comment]
@LyndseyPaxton, @ahaleiii , @gregpakes - The rollout was complete on July 31st. I've reached out to the PM who authored this article for more information. Will update you as soon as I get a response.

**Comment by divais** [comment]
We hit some deployment blocker and thus isn't not enabled. Hoping to complete the rollout in next 2-3 days. Sorry for the delay.

**Comment by divais** [comment]
Sorry reopening the issue, I closed it in err. I will close it when the deployment is complete for all customers.

**Comment by LyndseyPaxton** [comment]
Hi @divais,

Any update on the deployment?
Thanks

**Comment by iansul** [comment]
Ping. I thought I saw the settings light up in my account at some point, but they aren't there now. Any updates?

**Comment by divais** [comment]
Flaky feature is not enabled on all accounts. Do reach us if you face any issues.

**Comment by gregpakes** [comment]
Why closed?

**Comment by divais** [comment]
I closed it as the key concern was feature unavailability. Are you seeing issues? Do you prefer reopening?

**Comment by gregpakes** [comment]
Well - It's still not enabled in my account....  So if you close, I'm just going to open another asking why it's not enabled in my account....

**Comment by divais** [comment]
@gregpakes deleted your comment in err, trying to remove the emoji. Is it possible to share your account name.

**Comment by gregpakes** [comment]
publicly? privately?

**Comment by divais** [comment]
can you please send the details to devops_tools @ microsoft.com

**Comment by gregpakes** [comment]
I received a bounce saying:

> The group xxxx only accepts messages from people in its organization or on its allowed senders list, and your email address isn't on the list.

**Comment by gregpakes** [comment]
Done

**Comment by divais** [comment]
I did receive your email and responded back. Based on your system we see that flaky feature is enabled for your account.

**Comment by LyndseyPaxton** [comment]
Hi @divais 

I just checked one of my projects in Azure DevOps, and the menu item is still not there.

Are you able to check if it is enabled for my account please?

Thanks
LP

**Comment by LyndseyPaxton** [comment]
Okay, I do see it in 

Project Settings -> Test management 

Thanks for your help. Feel free to close the ticket.

Cheers
LP

**Comment by gregpakes** [comment]
All looks good.

**Comment by divais** [comment]
Flaky settings are available in Project setting under Test management. Sample below with default settings. 
![image](https://user-images.githubusercontent.com/17335060/63253405-6c9f4580-c28f-11e9-9692-c3d5e5e6c96e.png)

**Comment by zhongyi-zhang** [comment]
Hi @divais, I sent an email to devops_tools@microsoft.com. Could you help enable Flaky Test Management for us? Thanks

**Comment by upadhyayap** [comment]
@zhongyi-zhang It is now enabled. could you please try and let us know.
